### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/crossbuild#2]
Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/sync-labels.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md

**Comment by umbynos** [comment]
#5 should unlock https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md

**Comment by MatteoPologruto** [comment]
Sync-labels and the other checks added in the following PRs:
- sync-labels: #3 
- check-markdown-task: #4 
- check-license: #6 
- check-taskfiles: #7

**Comment by umbynos** [comment]
Adding https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-shell-task.md should be beneficial too

**Comment by umbynos** [comment]
needs investigating on how to filter the shell files

**Comment by MatteoPologruto** [comment]
check-shell-task: https://github.com/arduino/crossbuild/pull/11
